### ISSUE TITLE
Minor issues building Daikon with Dockerfile

### ISSUE THREAD

**Issue by VHellendoorn** [codespecs/daikon#162]
Using one of the provided Docker image (specifically, `Dockerfile-ubuntu-jdk8`) to recompile Daikon (in my case, rebuild the Daikon Jar), I ran into two small issues that may not necessarily be bugs (hence no PR) but may be worth inspecting:

- Line 57 of java/Makefile sets the `-Werror` flag. This causes the program to exit in case of compile warnings; since there are about 47 such warnings (many for seemingly insignificant issues), I had to remove this flag to allow full compilation.
- The build script relies on the rsync package, which is not included in the Dockerfile.
I can send a PR fixing either/both of the above, but figured I'd first check if/to what extent these are design decisions

**Comment by mernst** [comment]
Thanks for pointing out these problems.  (And, I apologize that you ran into trouble.)

We would like to fix these things, so we would welcome pull requests (separately for the separate issues, please).

It's probably best to fix the warnings rather than removing `-werror`, if possible.  Can you tell me what they are?  I'm curious why the Travis jobs are not failing, since they do build `daikon.jar`.  Are you working from a release or from head?

The dockerfile should definitely include the rsync package.

Thanks!

**Comment by VHellendoorn** [comment]
I'm building from HEAD (8bb826a); submitted PR #163 just now for the `rsync` issue.

As for `-Werror`, the warnings are all related to deprecation. Two samples demonstrating the two 
(very similar) categories:
```
./daikon/chicory/PureMethodInfo.java:70: warning: [deprecation] isAccessible() in AccessibleObject has been deprecated
    if (!meth.isAccessible()) {
             ^
./daikon/config/InvariantDoclet.java:54: warning: [removal] RootDoc in com.sun.javadoc has been deprecated and marked for removal
  public static boolean start(RootDoc doc) throws IOException {
```
I suppose the choice would be between suppressing `[deprecation]` and `[removal]` warnings or `-Werror`; I agree that keeping the latter is preferable. Please see PR #164

**Comment by mernst** [comment]
I'm closing this because #163 and #164 have been closed.  Thanks for those pull requests!
