### ISSUE TITLE
Junit with Daikon

### ISSUE THREAD

**Issue by thanhdeku** [codespecs/daikon#304]
Hi, I'm trying to run Daikon on Junit tests for dataset Defects4j. The tests run fine 
*Enviroment:
- Java: Openjdk version "1.8.0_275"
	    OpenJDK Runtime Environment (build 1.8.0_275-b01)
	    OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
- Daikon: 5.8.6
- Junit: 4.13.1

* I used a test runner written by Bo Yang ( https://github.com/boyang9602/APR_resources/blob/master/scripts/launcher/TestRunner.java) to execute test cases. 

* The tests run fine when I run them independently with command: java -cp /home/thanhlc:/home/thanhlc/junit-4.13.1.jar:/home/thanhlc/hamcrest-2.2.jar:build-tests:./target/test-classes:./target/classes:./target/tests:/home/thanhlc/library/daikonparent/daikon-5.8.6/daikon.jar TestRunner org.apache.commons.math3.util.MathArraysTest::testLinearCombinationWithSingleElementArray

* However, when I run them with Daikon: java -cp /home/thanhlc:/home/thanhlc/junit-4.13.1.jar:/home/thanhlc/hamcrest-2.2.jar:build-tests:./target/test-classes:./target/classes:./target/tests:/home/thanhlc/library/daikonparent/daikon-5.8.6/daikon.jar daikon.DynComp TestRunner org.apache.commons.math3.util.MathArraysTest::testLinearCombinationWithSingleElementArray 
===>  I get:
[initializationError(org.apache.commons.math3.util.MathArraysTest): Test class can only have one constructor

 I am wondering if you can give me some advices. Thank you very much.

**Comment by markro49** [comment]
You did not supply your test's code nor how to build it so I can only speculate as to the problem.  The error message suggests that you did not properly identify your junit test class.  This can be done in one of two ways:
-  the class is a subclass of junit.framework.TestCase
-  the test methods have a RuntimeVisibleAnnotation of org/junit/Test.
If you have done this, then you need to supply your test, how to build it and any jar files required so that we can try to duplicate and debug your problem.

**Comment by thanhdeku** [comment]
> You did not supply your test's code nor how to build it so I can only speculate as to the problem. The error message suggests that you did not properly identify your junit test class. This can be done in one of two ways:
> 
> * the class is a subclass of junit.framework.TestCase
> * the test methods have a RuntimeVisibleAnnotation of org/junit/Test.
> 
> If you have done this, then you need to supply your test, how to build it and any jar files required so that we can try to duplicate and debug your problem.

I'm so sorry about the lack of my test's code. I have already upload the project to Github. You can find this project in [https://github.com/thanhdeku/math3f](https://github.com/thanhdeku/math3f). This project is a part of dataset Defects4j (https://github.com/rjust/defects4j). So we used command provided defects4j to build this project. Specifically, we have did the following:
- Install defects4j
- Clone the project Math3f: defects4j checkout -p Math -v 3b -w math3f
- Compile the project: defects4j compile
- To run test case we used a test runner written by Bo Yang ( https://github.com/boyang9602/APR_resources/blob/master/scripts/launcher/TestRunner.java) to execute test cases. We compile and copy the test runnner to Math3f project
- Finally, we run with Daikon: java -cp /home/thanhlc:/home/thanhlc/junit-4.13.1.jar:/home/thanhlc/hamcrest-2.2.jar:build-tests:./target/test-classes:./target/classes:./target/tests:/home/thanhlc/library/daikonparent/daikon-5.8.6/daikon.jar daikon.DynComp TestRunner org.apache.commons.math3.util.MathArraysTest::testLinearCombinationWithSingleElementArray
I

**Comment by markro49** [comment]
The problem is using TestRunner to run the test cases.  It calls Class.forName() on the test class which causes it to be loaded before DynComp is ready.  The traditional way to do this is to use org.junit.runner.JUnitCore <test class>.  However, I see you are trying to call a single method of the class and JUnitCore does not support this.  I got around this by writing a little helper class
[tr3.txt](https://github.com/codespecs/daikon/files/5907859/tr3.txt)
that looks like a traditional JUnit test class and calls org.apache.commons.math3.util.MathArraysTest::testLinearCombinationWithSingleElementArray
So my command line was 
java -cp .:/homes/gws/markro/invariants/daikon/daikon.jar:target/classes:target/test-classes daikon.DynComp org.junit.runner.JUnitCore tr3
and this worked just fine.  Granted you lose the ability to do this on the command line and have to write a helper for each method or set of methods you wish to test, but it was the only way I could see to avoid the Class.forName() problem.

**Comment by thanhdeku** [comment]
Thank you so much for your kind response.

**Comment by markro49** [comment]
The size of the instrumented FastMathLiteralArrays.<clinit> is too large for the Java Class file.  We have code to deal with this, but <clinit> and 'main' are special cases (they cannot be duplicated) and we were not checking the size for these two.  I have a fix that I am testing.
