### ISSUE TITLE
Disabled Kvasir test: povray

### ISSUE THREAD

**Issue by mernst** [codespecs/daikon#4]
Originally reported on Google Code with ID 4

```
Several tests are disabled in the nightly Kvasir tests.
Search for "medium-easy-tests" in invariants/tests/kvasir-tests/Makefile.
These should be re-enabled, and the bugs that they reveal should be fixed.
```

Reported by `michael.ernst` on 2010-05-03 04:10:24

**Comment by markro49** [comment]
It does not seem possible, at this time, to get this test to pass on all platforms.  It is written in C++ and uses lots of the tricky bits.  The generated Dwarf code turns out to be very compiler dependent.

In addition, the test case itself is timing dependent and X11 enabled dependent. So either we need a unique set of goal files for each compiler/system combination or we just leave it turned off.  We have opted for the later.
