### ISSUE TITLE
Daikon filter (--ppt-select-pattern) with frequent exceptions and no invariants out

### ISSUE THREAD

**Issue by ybank** [codespecs/daikon#50]
Daikon version: 5.2.0
JDK version: 1.7.0_71
System: Mac OS El Capitan (10.11.3)
Description:

========
For the given dtrace file (shared), I execute Daikon on it and it works as normal. The command I run is:

java daikon.Daikon bug_report.dtrace.gz

The method I am interested is org.apache.commons.bcel6.util.Class2HTML.Class2HTML(..), which is the contructor for Class2HTML class. In the output of the above command, the invariants are there, also the Class invariants and Object invariants for that class are both there. All looks great.

However, when I need to get exactly that method's invariants using --ppt-select-pattern, on the exactly same dtrace file, it encounters a weird exception. The command I run and the exception is as follows: (its full output is shared in a file.)

java daikon.Daikon bug_report.dtrace.gz --ppt-select-pattern='^org\\.apache\\.commons\\.bcel6\\.util\\.Class2HTML\\.Class2HTML\\('

Exception in thread "main" java.lang.RuntimeException: parent ppt org.apache.commons.bcel6.util.Class2HTML:::OBJECT not found for ppt org.apache.commons.bcel6.util.Class2HTML.Class2HTML(org.apache.commons.bcel6.classfile.JavaClass, java.lang.String):::EXIT
at daikon.PptRelation.init_hierarchy_new(PptRelation.java:982)
at daikon.Daikon.process_data(Daikon.java:1954)
at daikon.Daikon.mainHelper(Daikon.java:573)
at daikon.Daikon.main(Daikon.java:453)

What is odd, is that what is complained in the exception seems not true, because in the previous execution (without filter) the Object invariants are indeed in the output. 

Looks like the -ppt-select-pattern filter does not work correctly in this case. 

========

To recreate the bug:

Because of the large file size, all of the files required to recreate the bug are uploaded online instead of being attached in this report. You can find and download them [here](https://goo.gl/fyuTP4). If this link does not work, you can copy and paste the url below to open files.

https://drive.google.com/folderview?id=0B2ErS1V8NMeXRkNuclVpQUJUNFE&usp=sharing

There are three files shared:

bug_report.dtrace.gz - the dtrace file to extract invariants from

full_inv_out.txt - the full output after executing without filter:
    java daikon.Daikon bug_report.dtrace.gz
(You will see the invariants there)

filter_inv_out.txt - the full output (with all exception information) after executing Daikon with filter:
    java daikon.Daikon bug_report.dtrace.gz --ppt-select-pattern='^org\\.apache\\.commons\\.bcel6\\.util\\.Class2HTML\\.Class2HTML\\('
(You will see the exception and no invariants are extracted)

**Comment by mernst** [comment]
Thanks for reporting the problem.
And thanks for providing a complete bug report, which really helps us.

This behavior is expected, but I can see that it could be surprising.  I'll tell you how to work around the problem, and we will also think about how to improve Daikon to be less surprising.

The `--ppt-select-pattern=`*ppt_regexp* command-line argument means that Daikon will only see the matching program points -- it's as if all the other program points in the file were removed from the file before Daikon was run.

Therefore, the error message
  parent ppt org.apache.commons.bcel6.util.Class2HTML:::OBJECT not found
is true:  that program point isn't in the part of the file that Daikon sees.

Furthermore, Note that the declaration of the :::EXIT109 program point of the method you are interested in, org.apache.commons.bcel6.util.Class2HTML.Class2HTML(..) on line 589082641 of file bug_report.dtrace, mentions org.apache.commons.bcel6.util.Class2HTML:::OBJECT and therefore Class2HTML.Class2HTML cannot be processed without Class2HTML:::OBJECT.

Solution 1:  The best solution is for you to supply a --ppt-select-pattern= regular expression that includes all the program points that are needed to produce output for the program point you are really interested in.  This includes the Class2HTML:::OBJECT program point.  Daikon's output will contain invariants for all the methods that match the --ppt-select-pattern regular expression, but it's easy to extract just the part that you care about.

Solution 2:  Change the declaration of the Class2HTML.Class2HTML program point to not mention any other program points.  Note that this could change Daikon's output:  you would see, at the Class2HTML.Class2HTML program point, any any output that is ordinarily suppressed because it is also true at the object program point.

Regarding possible change to Daikon:
 * For Solution 1:  Daikon cannot automatically include needed program points without reading the entire .dtrace file twice, because the needed program points' declarations precede the declaration of the method that matches the --ppt-select-pattern argument, and their samples may too.
 * For Solution 2:  Daikon could change declarations to not mention any program point that does not match the --ppt-select-pattern.  As noted above, this could change the output, but that might be OK.

**Comment by ybank** [comment]
Billion thanks for the detailed explanation and suggested solutions, Mike. It makes perfect sense now. I believe solution 1 is the best way to go, as you suggested. That can save huge space and time and makes all practical.

As a follow-up, that raises an immediate question: what are the needed program points? This really depends on what you mean by one ppt "mentioned" another one, in your reply. From Daikon's developer manual, [A.3.2 Program point declarations](http://plse.cs.washington.edu/daikon/download/doc/developer.html#Program-point-declarations), it seems the only (right?) possible mentioning is the parent field, where two relationships are possible: parent and user. The user relations are by default not used, so I believe I only need to consider parent relationship. Then from Daikon's developer manual, [4.2 Dataflow hierarchy](http://plse.cs.washington.edu/daikon/download/doc/developer.html#Dataflow-hierarchy), with the four ways ppts relate, if we are interested in only some *method* mtd(P p, Q q) of a class C (with package pkg.to), then the needed ppts that should be included in the --ppt-select-pattern filter are:
- pkg.to.C.mtd(
- pkg.to.C.
- pkg.to.A, pkg.to.B, ... (where A, B, ... are all of C's super classes, interfaces, etc.)
- some.other.pkg.to.P, yet.another.pkg.to.Q (where P, Q, ... are classes of mtd's parameters)

Could you help me confirm or correct the above?

Thank you!
--Yan

BTW: while reading the manual there seems a typo, at [4.2 Dataflow hierarchy](http://plse.cs.washington.edu/daikon/download/doc/developer.html#Dataflow-hierarchy), the last sentence of last paragraph, "When dataflow is enabled, ..." should be "When dataflow is disabled, ...", I guess.

**Comment by mernst** [comment]
That sounds right overall.

You are right that only the parent program point relation is used now, though others could be used in the future.  I believe that Daikon hard-codes some relationships, such as between :::ENTER and :::EXIT program points, that should really be expressed in the dtrace file.

Including all of `pkg.to.C.` seems like overkill because it will include every method in C even though you are only interested in one of them.  You are most interested in the object program point, I believe.  The same comment applies to superclasses.  (But, I haven't tried this myself just now.)

The "when dataflow is *enabled*" text is correct, because invariants at all other locations can be inferred from just the data at :::EXIT program points.  For example, Daikon does not need to examine data at :::ENTER or :::OBJECT program points which are parents of @:::EXIT in the dataflow hierarchy.  I updated the manual to clarify this point.
