### ISSUE TITLE
Mismatch between .dtrace file and .decls file

### ISSUE THREAD

**Issue by vucinic** [codespecs/daikon#74]
Running Daikon on dtrace file generated by Kvasir the following output is given:
```
Daikon version 5.2.21, released January 6, 2016; http://plse.cs.washington.edu/daikon.
Processing trace data; reading 1 dtrace file:                                  
[12:26:29 PM]: Reading bzip2.dtrace (line 41974, 86.31%) ...                   Error at line 43470 in file bzip2.dtrace: Mismatch between .dtrace file and .decls file.  Expected variable to, got  for program point bzip2.c.copyFileName():::ENTER
```
Step to reproduce
- download Bzip2 source from <http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz>
- extract the archive, move into bzip2 folder and build the Bzip2 binary adding Dwarf symbols: <br />
   `make bzip2 CC="gcc -g -gdwarf-2"`
- launch Kvasir on binary:<br />
  ` kvasir-dtrace ./bzip2 -k -z  <a-file-to-compress>`
- move to `daikon-output` folder and run daikon:<br />
  `java daikon.Daikon bzip2.dtrace`

**Comment by markro49** [comment]
I'm sorry you're having trouble with Daikon.  Your description of how to reproduce the problem looks good and I will try to do so shortly.  In the meantime, would it be possible for you to try our current release 5.3.8 at http://plse.cs.washington.edu/daikon/download/?

**Comment by vucinic** [comment]
No problem, I'll have a try. 
I upload here the .dtrace file that caused the error (file name has been modified by adding ".txt" just to make github accept it for upload).

[bzip2.dtrace.txt](https://github.com/codespecs/daikon/files/447506/bzip2.dtrace.txt)

**Comment by markro49** [comment]
The problem is the Makefile sets the compiler optimization level at -O2 and a program must be compiled with no optimizations for Kvasir to work properly.  See http://plse.cs.washington.edu/daikon/download/doc/daikon.html#Kvasir.
When I modified the setting of CFLAGS in Makefile to remove -O2, everything worked as expected.

Please note that bzip2 does a very intensive computation on every byte to be compressed.  We use bzip2 as one of our test cases, but our sample input file is only 50 bytes long.  If you want to gather trace data on larger input files I highly recommend you read http://plse.cs.washington.edu/daikon/download/doc/daikon.html#Tracing-only-part-of-a-program for techniques to reduce the size of dtrace files.   For example, as part of testing this version of bzip2, I used the --dump-ppt-file option, editted the resulting file to comment out this core computation:
#compress.c.bsW()
#compress.c.bsPutUInt32()
#compress.c.bsPutUChar()

and then used the --ppt-list-file option to pass the edited ppt list file to Kvasir.

Let us know if we can be of further assistance.
Mark
